version: '3.8'
services:
  go-backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - AWS_ACCESS_KEY_ID=AKIAZLYLZRLIFNTLSADM
      - AWS_SECRET_ACCESS_KEY=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
      - AWS_REGION=eu-north-1

    networks:
      - app-network

  react-frontend:
    build:
      context: ./Frontend/counter-app
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
