version: '3.8'
services:
  go-backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network

  react-frontend:
    build:
      context: ./Frontend/counter-app
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
